# This is a basic workflow to help you get started with Actions

name: Pack JS files

env:
  doc_name: SkyRegionEditor

defaults:
  run:
    shell: bash
    working-directory: js

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cat utils.js > ${{ env.doc_name }}.js
          cat AstroCoo.js >> ${{ env.doc_name }}.js
          cat Segment.js >> ${{ env.doc_name }}.js
          cat STCRegion.js >> ${{ env.doc_name }}.js
          cat RegionEditor_v.js >> ${{ env.doc_name }}.js
          cat RegionEditor_c.js >> ${{ env.doc_name }}.js
          cat RegionEditor_m.js >> ${{ env.doc_name }}.js
          cat PublicApi.js >> ${{ env.doc_name }}.js

      - name: Check the output
        run: |
          ls
          test -f ${{ env.doc_name }}.js
          
      - name: Move the packed tag
        uses: weareyipyip/walking-tag-action@v1
        with:
          TAG_NAME: packed-JS
          TAG_MESSAGE: |
            Last commit taken into account for the JS packaging.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Update the PDF preview
        uses: Xotl/cool-github-releases@v1
        with:
          mode: update
          isPrerelease: true
          tag_name: packed-JS
          release_name: "Packed JS"
          body_mrkdwn: |
            This release aims to provide a packed JS of the last commit.
            _Corresponding commit: ${{ github.sha }}_
          assets: js/${{ env.doc_name }}.js
          replace_assets: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
